# Generated by Django 5.0 on 2023-12-21 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_purchased', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('season', models.CharField(max_length=50)),
                ('review_rating', models.IntegerField()),
                ('subscription_status', models.BooleanField()),
                ('payment_method', models.CharField(max_length=50)),
                ('shipping_type', models.CharField(max_length=50)),
                ('discount_applied', models.BooleanField()),
                ('promo_code_used', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_purchases', models.IntegerField()),
                ('frequency_of_purchases', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers_data.customer')),
            ],
        ),
    ]
