# Generated by Django 5.0 on 2023-12-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_data', '0002_alter_purchase_frequency_of_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mail',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
